#include <gl.h>

void (*__stdcall glBlendColor)(GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha);
void (*__stdcall glBlendEquation)(GLenum mode);
void (*__stdcall glDrawRangeElements)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices);
void (*__stdcall glColorTable)(GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table);
void (*__stdcall glColorTableParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
void (*__stdcall glColorTableParameteriv)(GLenum target, GLenum pname, const GLint *params);
void (*__stdcall glCopyColorTable)(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
void (*__stdcall glGetColorTable)(GLenum target, GLenum format, GLenum type, GLvoid *table);
void (*__stdcall glGetColorTableParameterfv)(GLenum target, GLenum pname, GLfloat *params);
void (*__stdcall glGetColorTableParameteriv)(GLenum target, GLenum pname, GLint *params);
void (*__stdcall glColorSubTable)(GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *data);
void (*__stdcall glCopyColorSubTable)(GLenum target, GLsizei start, GLint x, GLint y, GLsizei width);
void (*__stdcall glConvolutionFilter1D)(GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *image);
void (*__stdcall glConvolutionFilter2D)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *image);
void (*__stdcall glConvolutionParameterf)(GLenum target, GLenum pname, GLfloat params);
void (*__stdcall glConvolutionParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
void (*__stdcall glConvolutionParameteri)(GLenum target, GLenum pname, GLint params);
void (*__stdcall glConvolutionParameteriv)(GLenum target, GLenum pname, const GLint *params);
void (*__stdcall glCopyConvolutionFilter1D)(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width);
void (*__stdcall glCopyConvolutionFilter2D)(GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height);
void (*__stdcall glGetConvolutionFilter)(GLenum target, GLenum format, GLenum type, GLvoid *image);
void (*__stdcall glGetConvolutionParameterfv)(GLenum target, GLenum pname, GLfloat *params);
void (*__stdcall glGetConvolutionParameteriv)(GLenum target, GLenum pname, GLint *params);
void (*__stdcall glGetSeparableFilter)(GLenum target, GLenum format, GLenum type, GLvoid *row, GLvoid *column, GLvoid *span);
void (*__stdcall glSeparableFilter2D)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *row, const GLvoid *column);
void (*__stdcall glGetHistogram)(GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values);
void (*__stdcall glGetHistogramParameterfv)(GLenum target, GLenum pname, GLfloat *params);
void (*__stdcall glGetHistogramParameteriv)(GLenum target, GLenum pname, GLint *params);
void (*__stdcall glGetMinmax)(GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values);
void (*__stdcall glGetMinmaxParameterfv)(GLenum target, GLenum pname, GLfloat *params);
void (*__stdcall glGetMinmaxParameteriv)(GLenum target, GLenum pname, GLint *params);
void (*__stdcall glHistogram)(GLenum target, GLsizei width, GLenum internalformat, GLboolean sink);
void (*__stdcall glMinmax)(GLenum target, GLenum internalformat, GLboolean sink);
void (*__stdcall glResetHistogram)(GLenum target);
void (*__stdcall glResetMinmax)(GLenum target);
void (*__stdcall glTexImage3D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels);
void (*__stdcall glTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels);
void (*__stdcall glCopyTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void (*__stdcall glActiveTexture)(GLenum texture);
void (*__stdcall glClientActiveTexture)(GLenum texture);
void (*__stdcall glMultiTexCoord1d)(GLenum target, GLdouble s);
void (*__stdcall glMultiTexCoord1dv)(GLenum target, const GLdouble *v);
void (*__stdcall glMultiTexCoord1f)(GLenum target, GLfloat s);
void (*__stdcall glMultiTexCoord1fv)(GLenum target, const GLfloat *v);
void (*__stdcall glMultiTexCoord1i)(GLenum target, GLint s);
void (*__stdcall glMultiTexCoord1iv)(GLenum target, const GLint *v);
void (*__stdcall glMultiTexCoord1s)(GLenum target, GLshort s);
void (*__stdcall glMultiTexCoord1sv)(GLenum target, const GLshort *v);
void (*__stdcall glMultiTexCoord2d)(GLenum target, GLdouble s, GLdouble t);
void (*__stdcall glMultiTexCoord2dv)(GLenum target, const GLdouble *v);
void (*__stdcall glMultiTexCoord2f)(GLenum target, GLfloat s, GLfloat t);
void (*__stdcall glMultiTexCoord2fv)(GLenum target, const GLfloat *v);
void (*__stdcall glMultiTexCoord2i)(GLenum target, GLint s, GLint t);
void (*__stdcall glMultiTexCoord2iv)(GLenum target, const GLint *v);
void (*__stdcall glMultiTexCoord2s)(GLenum target, GLshort s, GLshort t);
void (*__stdcall glMultiTexCoord2sv)(GLenum target, const GLshort *v);
void (*__stdcall glMultiTexCoord3d)(GLenum target, GLdouble s, GLdouble t, GLdouble r);
void (*__stdcall glMultiTexCoord3dv)(GLenum target, const GLdouble *v);
void (*__stdcall glMultiTexCoord3f)(GLenum target, GLfloat s, GLfloat t, GLfloat r);
void (*__stdcall glMultiTexCoord3fv)(GLenum target, const GLfloat *v);
void (*__stdcall glMultiTexCoord3i)(GLenum target, GLint s, GLint t, GLint r);
void (*__stdcall glMultiTexCoord3iv)(GLenum target, const GLint *v);
void (*__stdcall glMultiTexCoord3s)(GLenum target, GLshort s, GLshort t, GLshort r);
void (*__stdcall glMultiTexCoord3sv)(GLenum target, const GLshort *v);
void (*__stdcall glMultiTexCoord4d)(GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q);
void (*__stdcall glMultiTexCoord4dv)(GLenum target, const GLdouble *v);
void (*__stdcall glMultiTexCoord4f)(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
void (*__stdcall glMultiTexCoord4fv)(GLenum target, const GLfloat *v);
void (*__stdcall glMultiTexCoord4i)(GLenum target, GLint s, GLint t, GLint r, GLint q);
void (*__stdcall glMultiTexCoord4iv)(GLenum target, const GLint *v);
void (*__stdcall glMultiTexCoord4s)(GLenum target, GLshort s, GLshort t, GLshort r, GLshort q);
void (*__stdcall glMultiTexCoord4sv)(GLenum target, const GLshort *v);
void (*__stdcall glLoadTransposeMatrixf)(const GLfloat *m);
void (*__stdcall glLoadTransposeMatrixd)(const GLdouble *m);
void (*__stdcall glMultTransposeMatrixf)(const GLfloat *m);
void (*__stdcall glMultTransposeMatrixd)(const GLdouble *m);
void (*__stdcall glSampleCoverage)(GLclampf value, GLboolean invert);
void (*__stdcall glCompressedTexImage3D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data);
void (*__stdcall glCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data);
void (*__stdcall glCompressedTexImage1D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data);
void (*__stdcall glCompressedTexSubImage3D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data);
void (*__stdcall glCompressedTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data);
void (*__stdcall glCompressedTexSubImage1D)(GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data);
void (*__stdcall glGetCompressedTexImage)(GLenum target, GLint level, GLvoid *img);
void (*__stdcall glBlendFuncSeparate)(GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
void (*__stdcall glFogCoordf)(GLfloat coord);
void (*__stdcall glFogCoordfv)(const GLfloat *coord);
void (*__stdcall glFogCoordd)(GLdouble coord);
void (*__stdcall glFogCoorddv)(const GLdouble *coord);
void (*__stdcall glFogCoordPointer)(GLenum type, GLsizei stride, const GLvoid *pointer);
void (*__stdcall glMultiDrawArrays)(GLenum mode, GLint *first, GLsizei *count, GLsizei primcount);
void (*__stdcall glMultiDrawElements)(GLenum mode, const GLsizei *count, GLenum type, const GLvoid* *indices, GLsizei primcount);
void (*__stdcall glPointParameterf)(GLenum pname, GLfloat param);
void (*__stdcall glPointParameterfv)(GLenum pname, const GLfloat *params);
void (*__stdcall glPointParameteri)(GLenum pname, GLint param);
void (*__stdcall glPointParameteriv)(GLenum pname, const GLint *params);
void (*__stdcall glSecondaryColor3b)(GLbyte red, GLbyte green, GLbyte blue);
void (*__stdcall glSecondaryColor3bv)(const GLbyte *v);
void (*__stdcall glSecondaryColor3d)(GLdouble red, GLdouble green, GLdouble blue);
void (*__stdcall glSecondaryColor3dv)(const GLdouble *v);
void (*__stdcall glSecondaryColor3f)(GLfloat red, GLfloat green, GLfloat blue);
void (*__stdcall glSecondaryColor3fv)(const GLfloat *v);
void (*__stdcall glSecondaryColor3i)(GLint red, GLint green, GLint blue);
void (*__stdcall glSecondaryColor3iv)(const GLint *v);
void (*__stdcall glSecondaryColor3s)(GLshort red, GLshort green, GLshort blue);
void (*__stdcall glSecondaryColor3sv)(const GLshort *v);
void (*__stdcall glSecondaryColor3ub)(GLubyte red, GLubyte green, GLubyte blue);
void (*__stdcall glSecondaryColor3ubv)(const GLubyte *v);
void (*__stdcall glSecondaryColor3ui)(GLuint red, GLuint green, GLuint blue);
void (*__stdcall glSecondaryColor3uiv)(const GLuint *v);
void (*__stdcall glSecondaryColor3us)(GLushort red, GLushort green, GLushort blue);
void (*__stdcall glSecondaryColor3usv)(const GLushort *v);
void (*__stdcall glSecondaryColorPointer)(GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void (*__stdcall glWindowPos2d)(GLdouble x, GLdouble y);
void (*__stdcall glWindowPos2dv)(const GLdouble *v);
void (*__stdcall glWindowPos2f)(GLfloat x, GLfloat y);
void (*__stdcall glWindowPos2fv)(const GLfloat *v);
void (*__stdcall glWindowPos2i)(GLint x, GLint y);
void (*__stdcall glWindowPos2iv)(const GLint *v);
void (*__stdcall glWindowPos2s)(GLshort x, GLshort y);
void (*__stdcall glWindowPos2sv)(const GLshort *v);
void (*__stdcall glWindowPos3d)(GLdouble x, GLdouble y, GLdouble z);
void (*__stdcall glWindowPos3dv)(const GLdouble *v);
void (*__stdcall glWindowPos3f)(GLfloat x, GLfloat y, GLfloat z);
void (*__stdcall glWindowPos3fv)(const GLfloat *v);
void (*__stdcall glWindowPos3i)(GLint x, GLint y, GLint z);
void (*__stdcall glWindowPos3iv)(const GLint *v);
void (*__stdcall glWindowPos3s)(GLshort x, GLshort y, GLshort z);
void (*__stdcall glWindowPos3sv)(const GLshort *v);
void (*__stdcall glGenQueries)(GLsizei n, GLuint *ids);
void (*__stdcall glDeleteQueries)(GLsizei n, const GLuint *ids);
GLboolean (*__stdcall glIsQuery)(GLuint id);
void (*__stdcall glBeginQuery)(GLenum target, GLuint id);
void (*__stdcall glEndQuery)(GLenum target);
void (*__stdcall glGetQueryiv)(GLenum target, GLenum pname, GLint *params);
void (*__stdcall glGetQueryObjectiv)(GLuint id, GLenum pname, GLint *params);
void (*__stdcall glGetQueryObjectuiv)(GLuint id, GLenum pname, GLuint *params);
void (*__stdcall glBindBuffer)(GLenum target, GLuint buffer);
void (*__stdcall glDeleteBuffers)(GLsizei n, const GLuint *buffers);
void (*__stdcall glGenBuffers)(GLsizei n, GLuint *buffers);
GLboolean (*__stdcall glIsBuffer)(GLuint buffer);
void (*__stdcall glBufferData)(GLenum target, GLsizeiptr size, const GLvoid *data, GLenum usage);
void (*__stdcall glBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const GLvoid *data);
void (*__stdcall glGetBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, GLvoid *data);
GLvoid* (*__stdcall glMapBuffer)(GLenum target, GLenum access);
GLboolean (*__stdcall glUnmapBuffer)(GLenum target);
void (*__stdcall glGetBufferParameteriv)(GLenum target, GLenum pname, GLint *params);
void (*__stdcall glGetBufferPointerv)(GLenum target, GLenum pname, GLvoid* *params);
void (*__stdcall glBlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha);
void (*__stdcall glDrawBuffers)(GLsizei n, const GLenum *bufs);
void (*__stdcall glStencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void (*__stdcall glStencilFuncSeparate)(GLenum frontfunc, GLenum backfunc, GLint ref, GLuint mask);
void (*__stdcall glStencilMaskSeparate)(GLenum face, GLuint mask);
void (*__stdcall glAttachShader)(GLuint program, GLuint shader);
void (*__stdcall glBindAttribLocation)(GLuint program, GLuint index, const GLchar *name);
void (*__stdcall glCompileShader)(GLuint shader);
GLuint (*__stdcall glCreateProgram)();
GLuint (*__stdcall glCreateShader)(GLenum type);
void (*__stdcall glDeleteProgram)(GLuint program);
void (*__stdcall glDeleteShader)(GLuint shader);
void (*__stdcall glDetachShader)(GLuint program, GLuint shader);
void (*__stdcall glDisableVertexAttribArray)(GLuint index);
void (*__stdcall glEnableVertexAttribArray)(GLuint index);
void (*__stdcall glGetActiveAttrib)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void (*__stdcall glGetActiveUniform)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void (*__stdcall glGetAttachedShaders)(GLuint program, GLsizei maxCount, GLsizei *count, GLuint *obj);
GLint (*__stdcall glGetAttribLocation)(GLuint program, const GLchar *name);
void (*__stdcall glGetProgramiv)(GLuint program, GLenum pname, GLint *params);
void (*__stdcall glGetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (*__stdcall glGetShaderiv)(GLuint shader, GLenum pname, GLint *params);
void (*__stdcall glGetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void (*__stdcall glGetShaderSource)(GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
GLint (*__stdcall glGetUniformLocation)(GLuint program, const GLchar *name);
void (*__stdcall glGetUniformfv)(GLuint program, GLint location, GLfloat *params);
void (*__stdcall glGetUniformiv)(GLuint program, GLint location, GLint *params);
void (*__stdcall glGetVertexAttribdv)(GLuint index, GLenum pname, GLdouble *params);
void (*__stdcall glGetVertexAttribfv)(GLuint index, GLenum pname, GLfloat *params);
void (*__stdcall glGetVertexAttribiv)(GLuint index, GLenum pname, GLint *params);
void (*__stdcall glGetVertexAttribPointerv)(GLuint index, GLenum pname, GLvoid* *pointer);
GLboolean (*__stdcall glIsProgram)(GLuint program);
GLboolean (*__stdcall glIsShader)(GLuint shader);
void (*__stdcall glLinkProgram)(GLuint program);
void (*__stdcall glShaderSource)(GLuint shader, GLsizei count, const GLchar* *string, const GLint *length);
void (*__stdcall glUseProgram)(GLuint program);
void (*__stdcall glUniform1f)(GLint location, GLfloat v0);
void (*__stdcall glUniform2f)(GLint location, GLfloat v0, GLfloat v1);
void (*__stdcall glUniform3f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void (*__stdcall glUniform4f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void (*__stdcall glUniform1i)(GLint location, GLint v0);
void (*__stdcall glUniform2i)(GLint location, GLint v0, GLint v1);
void (*__stdcall glUniform3i)(GLint location, GLint v0, GLint v1, GLint v2);
void (*__stdcall glUniform4i)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void (*__stdcall glUniform1fv)(GLint location, GLsizei count, const GLfloat *value);
void (*__stdcall glUniform2fv)(GLint location, GLsizei count, const GLfloat *value);
void (*__stdcall glUniform3fv)(GLint location, GLsizei count, const GLfloat *value);
void (*__stdcall glUniform4fv)(GLint location, GLsizei count, const GLfloat *value);
void (*__stdcall glUniform1iv)(GLint location, GLsizei count, const GLint *value);
void (*__stdcall glUniform2iv)(GLint location, GLsizei count, const GLint *value);
void (*__stdcall glUniform3iv)(GLint location, GLsizei count, const GLint *value);
void (*__stdcall glUniform4iv)(GLint location, GLsizei count, const GLint *value);
void (*__stdcall glUniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (*__stdcall glUniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (*__stdcall glUniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (*__stdcall glValidateProgram)(GLuint program);
void (*__stdcall glVertexAttrib1d)(GLuint index, GLdouble x);
void (*__stdcall glVertexAttrib1dv)(GLuint index, const GLdouble *v);
void (*__stdcall glVertexAttrib1f)(GLuint index, GLfloat x);
void (*__stdcall glVertexAttrib1fv)(GLuint index, const GLfloat *v);
void (*__stdcall glVertexAttrib1s)(GLuint index, GLshort x);
void (*__stdcall glVertexAttrib1sv)(GLuint index, const GLshort *v);
void (*__stdcall glVertexAttrib2d)(GLuint index, GLdouble x, GLdouble y);
void (*__stdcall glVertexAttrib2dv)(GLuint index, const GLdouble *v);
void (*__stdcall glVertexAttrib2f)(GLuint index, GLfloat x, GLfloat y);
void (*__stdcall glVertexAttrib2fv)(GLuint index, const GLfloat *v);
void (*__stdcall glVertexAttrib2s)(GLuint index, GLshort x, GLshort y);
void (*__stdcall glVertexAttrib2sv)(GLuint index, const GLshort *v);
void (*__stdcall glVertexAttrib3d)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
void (*__stdcall glVertexAttrib3dv)(GLuint index, const GLdouble *v);
void (*__stdcall glVertexAttrib3f)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
void (*__stdcall glVertexAttrib3fv)(GLuint index, const GLfloat *v);
void (*__stdcall glVertexAttrib3s)(GLuint index, GLshort x, GLshort y, GLshort z);
void (*__stdcall glVertexAttrib3sv)(GLuint index, const GLshort *v);
void (*__stdcall glVertexAttrib4Nbv)(GLuint index, const GLbyte *v);
void (*__stdcall glVertexAttrib4Niv)(GLuint index, const GLint *v);
void (*__stdcall glVertexAttrib4Nsv)(GLuint index, const GLshort *v);
void (*__stdcall glVertexAttrib4Nub)(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
void (*__stdcall glVertexAttrib4Nubv)(GLuint index, const GLubyte *v);
void (*__stdcall glVertexAttrib4Nuiv)(GLuint index, const GLuint *v);
void (*__stdcall glVertexAttrib4Nusv)(GLuint index, const GLushort *v);
void (*__stdcall glVertexAttrib4bv)(GLuint index, const GLbyte *v);
void (*__stdcall glVertexAttrib4d)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
void (*__stdcall glVertexAttrib4dv)(GLuint index, const GLdouble *v);
void (*__stdcall glVertexAttrib4f)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void (*__stdcall glVertexAttrib4fv)(GLuint index, const GLfloat *v);
void (*__stdcall glVertexAttrib4iv)(GLuint index, const GLint *v);
void (*__stdcall glVertexAttrib4s)(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w);
void (*__stdcall glVertexAttrib4sv)(GLuint index, const GLshort *v);
void (*__stdcall glVertexAttrib4ubv)(GLuint index, const GLubyte *v);
void (*__stdcall glVertexAttrib4uiv)(GLuint index, const GLuint *v);
void (*__stdcall glVertexAttrib4usv)(GLuint index, const GLushort *v);
void (*__stdcall glVertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const GLvoid *pointer);
void (*__stdcall glUniformMatrix2x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (*__stdcall glUniformMatrix3x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (*__stdcall glUniformMatrix2x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (*__stdcall glUniformMatrix4x2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (*__stdcall glUniformMatrix3x4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (*__stdcall glUniformMatrix4x3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void (*__stdcall glColorMaski)(GLuint index, GLboolean r, GLboolean g, GLboolean b, GLboolean a);
void (*__stdcall glGetBooleani_v)(GLenum target, GLuint index, GLboolean *data);
void (*__stdcall glGetIntegeri_v)(GLenum target, GLuint index, GLint *data);
void (*__stdcall glEnablei)(GLenum target, GLuint index);
void (*__stdcall glDisablei)(GLenum target, GLuint index);
GLboolean (*__stdcall glIsEnabledi)(GLenum target, GLuint index);
void (*__stdcall glBeginTransformFeedback)(GLenum primitiveMode);
void (*__stdcall glEndTransformFeedback)(void);
void (*__stdcall glBindBufferRange)(GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
void (*__stdcall glBindBufferBase)(GLenum target, GLuint index, GLuint buffer);
void (*__stdcall glTransformFeedbackVaryings)(GLuint program, GLsizei count, const GLchar **varyings, GLenum bufferMode);
void (*__stdcall glGetTransformFeedbackVarying)(GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name);
void (*__stdcall glClampColor)(GLenum target, GLenum clamp);
void (*__stdcall glBeginConditionalRender)(GLuint id, GLenum mode);
void (*__stdcall glEndConditionalRender)(void);
void (*__stdcall glVertexAttribI1i)(GLuint index, GLint x);
void (*__stdcall glVertexAttribI2i)(GLuint index, GLint x, GLint y);
void (*__stdcall glVertexAttribI3i)(GLuint index, GLint x, GLint y, GLint z);
void (*__stdcall glVertexAttribI4i)(GLuint index, GLint x, GLint y, GLint z, GLint w);
void (*__stdcall glVertexAttribI1ui)(GLuint index, GLuint x);
void (*__stdcall glVertexAttribI2ui)(GLuint index, GLuint x, GLuint y);
void (*__stdcall glVertexAttribI3ui)(GLuint index, GLuint x, GLuint y, GLuint z);
void (*__stdcall glVertexAttribI4ui)(GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
void (*__stdcall glVertexAttribI1iv)(GLuint index, const GLint *v);
void (*__stdcall glVertexAttribI2iv)(GLuint index, const GLint *v);
void (*__stdcall glVertexAttribI3iv)(GLuint index, const GLint *v);
void (*__stdcall glVertexAttribI4iv)(GLuint index, const GLint *v);
void (*__stdcall glVertexAttribI1uiv)(GLuint index, const GLuint *v);
void (*__stdcall glVertexAttribI2uiv)(GLuint index, const GLuint *v);
void (*__stdcall glVertexAttribI3uiv)(GLuint index, const GLuint *v);
void (*__stdcall glVertexAttribI4uiv)(GLuint index, const GLuint *v);
void (*__stdcall glVertexAttribI4bv)(GLuint index, const GLbyte *v);
void (*__stdcall glVertexAttribI4sv)(GLuint index, const GLshort *v);
void (*__stdcall glVertexAttribI4ubv)(GLuint index, const GLubyte *v);
void (*__stdcall glVertexAttribI4usv)(GLuint index, const GLushort *v);
void (*__stdcall glVertexAttribIPointer)(GLuint index, GLint size, GLenum type, GLsizei stride, const GLvoid *pointer);
void (*__stdcall glGetVertexAttribIiv)(GLuint index, GLenum pname, GLint *params);
void (*__stdcall glGetVertexAttribIuiv)(GLuint index, GLenum pname, GLuint *params);
void (*__stdcall glGetUniformuiv)(GLuint program, GLint location, GLuint *params);
void (*__stdcall glBindFragDataLocation)(GLuint program, GLuint color, const GLchar *name);
GLint (*__stdcall glGetFragDataLocation)(GLuint program, const GLchar *name);
void (*__stdcall glUniform1ui)(GLint location, GLuint v0);
void (*__stdcall glUniform2ui)(GLint location, GLuint v0, GLuint v1);
void (*__stdcall glUniform3ui)(GLint location, GLuint v0, GLuint v1, GLuint v2);
void (*__stdcall glUniform4ui)(GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void (*__stdcall glUniform1uiv)(GLint location, GLsizei count, const GLuint *value);
void (*__stdcall glUniform2uiv)(GLint location, GLsizei count, const GLuint *value);
void (*__stdcall glUniform3uiv)(GLint location, GLsizei count, const GLuint *value);
void (*__stdcall glUniform4uiv)(GLint location, GLsizei count, const GLuint *value);
void (*__stdcall glTexParameterIiv)(GLenum target, GLenum pname, const GLint *params);
void (*__stdcall glTexParameterIuiv)(GLenum target, GLenum pname, const GLuint *params);
void (*__stdcall glGetTexParameterIiv)(GLenum target, GLenum pname, GLint *params);
void (*__stdcall glGetTexParameterIuiv)(GLenum target, GLenum pname, GLuint *params);
void (*__stdcall glClearBufferiv)(GLenum buffer, GLint drawbuffer, const GLint *value);
void (*__stdcall glClearBufferuiv)(GLenum buffer, GLint drawbuffer, const GLuint *value);
void (*__stdcall glClearBufferfv)(GLenum buffer, GLint drawbuffer, const GLfloat *value);
void (*__stdcall glClearBufferfi)(GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
GLboolean (*__stdcall glIsRenderbuffer)(GLuint renderbuffer);
void (*__stdcall glBindRenderbuffer)(GLenum target, GLuint renderbuffer);
void (*__stdcall glDeleteRenderbuffers)(GLsizei n, const GLuint *renderbuffers);
void (*__stdcall glGenRenderbuffers)(GLsizei n, GLuint *renderbuffers);
void (*__stdcall glRenderbufferStorage)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
void (*__stdcall glGetRenderbufferParameteriv)(GLenum target, GLenum pname, GLint *params);
GLboolean (*__stdcall glIsFramebuffer)(GLuint framebuffer);
void (*__stdcall glBindFramebuffer)(GLenum target, GLuint framebuffer);
void (*__stdcall glDeleteFramebuffers)(GLsizei n, const GLuint *framebuffers);
void (*__stdcall glGenFramebuffers)(GLsizei n, GLuint *framebuffers);
GLenum (*__stdcall glCheckFramebufferStatus)(GLenum target);
void (*__stdcall glFramebufferTexture1D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void (*__stdcall glFramebufferTexture2D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void (*__stdcall glFramebufferTexture3D)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level, GLint zoffset);
void (*__stdcall glFramebufferRenderbuffer)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void (*__stdcall glGetFramebufferAttachmentParameteriv)(GLenum target, GLenum attachment, GLenum pname, GLint *params);
void (*__stdcall glGenerateMipmap)(GLenum target);
void (*__stdcall glBlitFramebuffer)(GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
void (*__stdcall glRenderbufferStorageMultisample)(GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void (*__stdcall glFramebufferTextureLayer)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
void (*__stdcall glFlushMappedBufferRange)(GLenum target, GLintptr offset, GLsizeiptr length);
void (*__stdcall glBindVertexArray)(GLuint array);
void (*__stdcall glDeleteVertexArrays)(GLsizei n, const GLuint *arrays);
void (*__stdcall glGenVertexArrays)(GLsizei n, GLuint *arrays);
GLboolean (*__stdcall glIsVertexArray)(GLuint array);
void (*__stdcall glDrawArraysInstanced)(GLenum mode, GLint first, GLsizei count, GLsizei primcount);
void (*__stdcall glDrawElementsInstanced)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLsizei primcount);
void (*__stdcall glPrimitiveRestartIndex)(GLuint index);
void (*__stdcall glTexBuffer)(GLenum target, GLenum internalformat, GLuint buffer);
void (*__stdcall glCopyBufferSubData)(GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void (*__stdcall glGetActiveUniformBlockName)(GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
void (*__stdcall glGetActiveUniformBlockiv)(GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
void (*__stdcall glGetActiveUniformName)(GLuint program, GLuint uniformIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformName);
void (*__stdcall glGetActiveUniformsiv)(GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
GLuint (*__stdcall glGetUniformBlockIndex)(GLuint program, const GLchar *uniformBlockName);
void (*__stdcall glGetUniformIndices)(GLuint program, GLsizei uniformCount, const GLchar **uniformNames, GLuint *uniformIndices);
void (*__stdcall glUniformBlockBinding)(GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
void (*__stdcall glFramebufferTexture)(GLenum target, GLenum attachment, GLuint texture, GLint level);
void (*__stdcall glFramebufferTextureFace)(GLenum target, GLenum attachment, GLuint texture, GLint level, GLenum face);
void (*__stdcall glGetBufferParameteri64v)(GLenum target, GLenum pname, GLint64 *params);
void (*__stdcall glGetInteger64i_v)(GLenum target, GLuint index, GLint64 *data);
void (*__stdcall glProgramParameteri)(GLuint program, GLenum pname, GLint value);
void (*__stdcall glDrawElementsBaseVertex)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex);
void (*__stdcall glDrawElementsInstancedBaseVertex)(GLenum mode, GLsizei count, GLenum type, const GLvoid *indices, GLsizei primcount, GLint basevertex);
void (*__stdcall glDrawRangeElementsBaseVertex)(GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices, GLint basevertex);
void (*__stdcall glMultiDrawElementsBaseVertex)(GLenum mode, const GLsizei *count, GLenum type, const GLvoid **indices, GLsizei primcount, const GLint *basevertex);
void (*__stdcall glProvokingVertex)(GLenum mode);
GLenum (*__stdcall glClientWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
void (*__stdcall glDeleteSync)(GLsync sync);
GLsync (*__stdcall glFenceSync)(GLenum condition, GLbitfield flags);
void (*__stdcall glGetInteger64v)(GLenum pname, GLint64 *params);
void (*__stdcall glGetSynciv)(GLsync sync, GLenum pname, GLsizei bufSize, GLsizei *length, GLint *values);
GLboolean (*__stdcall glIsSync)(GLsync sync);
void (*__stdcall glWaitSync)(GLsync sync, GLbitfield flags, GLuint64 timeout);
void (*__stdcall glGetMultisamplefv)(GLenum pname, GLuint index, GLfloat *val);
void (*__stdcall glTexImage2DMultisample)(GLenum target, GLsizei samples, GLint internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
void (*__stdcall glTexImage3DMultisample)(GLenum target, GLsizei samples, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLboolean fixedsamplelocations);
void (*__stdcall glSampleMaski)(GLuint index, GLbitfield mask);

void InitializeGLFuncs()
{
    glBlendColor = wglGetProcAddress("glBlendColor");
    glBlendEquation = wglGetProcAddress("glBlendEquation");
    glDrawRangeElements = wglGetProcAddress("glDrawRangeElements");
    glColorTable = wglGetProcAddress("glColorTable");
    glColorTableParameterfv = wglGetProcAddress("glColorTableParameterfv");
    glColorTableParameteriv = wglGetProcAddress("glColorTableParameteriv");
    glCopyColorTable = wglGetProcAddress("glCopyColorTable");
    glGetColorTable = wglGetProcAddress("glGetColorTable");
    glGetColorTableParameterfv = wglGetProcAddress("glGetColorTableParameterfv");
    glGetColorTableParameteriv = wglGetProcAddress("glGetColorTableParameteriv");
    glColorSubTable = wglGetProcAddress("glColorSubTable");
    glCopyColorSubTable = wglGetProcAddress("glCopyColorSubTable");
    glConvolutionFilter1D = wglGetProcAddress("glConvolutionFilter1D");
    glConvolutionFilter2D = wglGetProcAddress("glConvolutionFilter2D");
    glConvolutionParameterf = wglGetProcAddress("glConvolutionParameterf");
    glConvolutionParameterfv = wglGetProcAddress("glConvolutionParameterfv");
    glConvolutionParameteri = wglGetProcAddress("glConvolutionParameteri");
    glConvolutionParameteriv = wglGetProcAddress("glConvolutionParameteriv");
    glCopyConvolutionFilter1D = wglGetProcAddress("glCopyConvolutionFilter1D");
    glCopyConvolutionFilter2D = wglGetProcAddress("glCopyConvolutionFilter2D");
    glGetConvolutionFilter = wglGetProcAddress("glGetConvolutionFilter");
    glGetConvolutionParameterfv = wglGetProcAddress("glGetConvolutionParameterfv");
    glGetConvolutionParameteriv = wglGetProcAddress("glGetConvolutionParameteriv");
    glGetSeparableFilter = wglGetProcAddress("glGetSeparableFilter");
    glSeparableFilter2D = wglGetProcAddress("glSeparableFilter2D");
    glGetHistogram = wglGetProcAddress("glGetHistogram");
    glGetHistogramParameterfv = wglGetProcAddress("glGetHistogramParameterfv");
    glGetHistogramParameteriv = wglGetProcAddress("glGetHistogramParameteriv");
    glGetMinmax = wglGetProcAddress("glGetMinmax");
    glGetMinmaxParameterfv = wglGetProcAddress("glGetMinmaxParameterfv");
    glGetMinmaxParameteriv = wglGetProcAddress("glGetMinmaxParameteriv");
    glHistogram = wglGetProcAddress("glHistogram");
    glMinmax = wglGetProcAddress("glMinmax");
    glResetHistogram = wglGetProcAddress("glResetHistogram");
    glResetMinmax = wglGetProcAddress("glResetMinmax");
    glTexImage3D = wglGetProcAddress("glTexImage3D");
    glTexSubImage3D = wglGetProcAddress("glTexSubImage3D");
    glCopyTexSubImage3D = wglGetProcAddress("glCopyTexSubImage3D");
    glActiveTexture = wglGetProcAddress("glActiveTexture");
    glClientActiveTexture = wglGetProcAddress("glClientActiveTexture");
    glMultiTexCoord1d = wglGetProcAddress("glMultiTexCoord1d");
    glMultiTexCoord1dv = wglGetProcAddress("glMultiTexCoord1dv");
    glMultiTexCoord1f = wglGetProcAddress("glMultiTexCoord1f");
    glMultiTexCoord1fv = wglGetProcAddress("glMultiTexCoord1fv");
    glMultiTexCoord1i = wglGetProcAddress("glMultiTexCoord1i");
    glMultiTexCoord1iv = wglGetProcAddress("glMultiTexCoord1iv");
    glMultiTexCoord1s = wglGetProcAddress("glMultiTexCoord1s");
    glMultiTexCoord1sv = wglGetProcAddress("glMultiTexCoord1sv");
    glMultiTexCoord2d = wglGetProcAddress("glMultiTexCoord2d");
    glMultiTexCoord2dv = wglGetProcAddress("glMultiTexCoord2dv");
    glMultiTexCoord2f = wglGetProcAddress("glMultiTexCoord2f");
    glMultiTexCoord2fv = wglGetProcAddress("glMultiTexCoord2fv");
    glMultiTexCoord2i = wglGetProcAddress("glMultiTexCoord2i");
    glMultiTexCoord2iv = wglGetProcAddress("glMultiTexCoord2iv");
    glMultiTexCoord2s = wglGetProcAddress("glMultiTexCoord2s");
    glMultiTexCoord2sv = wglGetProcAddress("glMultiTexCoord2sv");
    glMultiTexCoord3d = wglGetProcAddress("glMultiTexCoord3d");
    glMultiTexCoord3dv = wglGetProcAddress("glMultiTexCoord3dv");
    glMultiTexCoord3f = wglGetProcAddress("glMultiTexCoord3f");
    glMultiTexCoord3fv = wglGetProcAddress("glMultiTexCoord3fv");
    glMultiTexCoord3i = wglGetProcAddress("glMultiTexCoord3i");
    glMultiTexCoord3iv = wglGetProcAddress("glMultiTexCoord3iv");
    glMultiTexCoord3s = wglGetProcAddress("glMultiTexCoord3s");
    glMultiTexCoord3sv = wglGetProcAddress("glMultiTexCoord3sv");
    glMultiTexCoord4d = wglGetProcAddress("glMultiTexCoord4d");
    glMultiTexCoord4dv = wglGetProcAddress("glMultiTexCoord4dv");
    glMultiTexCoord4f = wglGetProcAddress("glMultiTexCoord4f");
    glMultiTexCoord4fv = wglGetProcAddress("glMultiTexCoord4fv");
    glMultiTexCoord4i = wglGetProcAddress("glMultiTexCoord4i");
    glMultiTexCoord4iv = wglGetProcAddress("glMultiTexCoord4iv");
    glMultiTexCoord4s = wglGetProcAddress("glMultiTexCoord4s");
    glMultiTexCoord4sv = wglGetProcAddress("glMultiTexCoord4sv");
    glLoadTransposeMatrixf = wglGetProcAddress("glLoadTransposeMatrixf");
    glLoadTransposeMatrixd = wglGetProcAddress("glLoadTransposeMatrixd");
    glMultTransposeMatrixf = wglGetProcAddress("glMultTransposeMatrixf");
    glMultTransposeMatrixd = wglGetProcAddress("glMultTransposeMatrixd");
    glSampleCoverage = wglGetProcAddress("glSampleCoverage");
    glCompressedTexImage3D = wglGetProcAddress("glCompressedTexImage3D");
    glCompressedTexImage2D = wglGetProcAddress("glCompressedTexImage2D");
    glCompressedTexImage1D = wglGetProcAddress("glCompressedTexImage1D");
    glCompressedTexSubImage3D = wglGetProcAddress("glCompressedTexSubImage3D");
    glCompressedTexSubImage2D = wglGetProcAddress("glCompressedTexSubImage2D");
    glCompressedTexSubImage1D = wglGetProcAddress("glCompressedTexSubImage1D");
    glGetCompressedTexImage = wglGetProcAddress("glGetCompressedTexImage");
    glBlendFuncSeparate = wglGetProcAddress("glBlendFuncSeparate");
    glFogCoordf = wglGetProcAddress("glFogCoordf");
    glFogCoordfv = wglGetProcAddress("glFogCoordfv");
    glFogCoordd = wglGetProcAddress("glFogCoordd");
    glFogCoorddv = wglGetProcAddress("glFogCoorddv");
    glFogCoordPointer = wglGetProcAddress("glFogCoordPointer");
    glMultiDrawArrays = wglGetProcAddress("glMultiDrawArrays");
    glMultiDrawElements = wglGetProcAddress("glMultiDrawElements");
    glPointParameterf = wglGetProcAddress("glPointParameterf");
    glPointParameterfv = wglGetProcAddress("glPointParameterfv");
    glPointParameteri = wglGetProcAddress("glPointParameteri");
    glPointParameteriv = wglGetProcAddress("glPointParameteriv");
    glSecondaryColor3b = wglGetProcAddress("glSecondaryColor3b");
    glSecondaryColor3bv = wglGetProcAddress("glSecondaryColor3bv");
    glSecondaryColor3d = wglGetProcAddress("glSecondaryColor3d");
    glSecondaryColor3dv = wglGetProcAddress("glSecondaryColor3dv");
    glSecondaryColor3f = wglGetProcAddress("glSecondaryColor3f");
    glSecondaryColor3fv = wglGetProcAddress("glSecondaryColor3fv");
    glSecondaryColor3i = wglGetProcAddress("glSecondaryColor3i");
    glSecondaryColor3iv = wglGetProcAddress("glSecondaryColor3iv");
    glSecondaryColor3s = wglGetProcAddress("glSecondaryColor3s");
    glSecondaryColor3sv = wglGetProcAddress("glSecondaryColor3sv");
    glSecondaryColor3ub = wglGetProcAddress("glSecondaryColor3ub");
    glSecondaryColor3ubv = wglGetProcAddress("glSecondaryColor3ubv");
    glSecondaryColor3ui = wglGetProcAddress("glSecondaryColor3ui");
    glSecondaryColor3uiv = wglGetProcAddress("glSecondaryColor3uiv");
    glSecondaryColor3us = wglGetProcAddress("glSecondaryColor3us");
    glSecondaryColor3usv = wglGetProcAddress("glSecondaryColor3usv");
    glSecondaryColorPointer = wglGetProcAddress("glSecondaryColorPointer");
    glWindowPos2d = wglGetProcAddress("glWindowPos2d");
    glWindowPos2dv = wglGetProcAddress("glWindowPos2dv");
    glWindowPos2f = wglGetProcAddress("glWindowPos2f");
    glWindowPos2fv = wglGetProcAddress("glWindowPos2fv");
    glWindowPos2i = wglGetProcAddress("glWindowPos2i");
    glWindowPos2iv = wglGetProcAddress("glWindowPos2iv");
    glWindowPos2s = wglGetProcAddress("glWindowPos2s");
    glWindowPos2sv = wglGetProcAddress("glWindowPos2sv");
    glWindowPos3d = wglGetProcAddress("glWindowPos3d");
    glWindowPos3dv = wglGetProcAddress("glWindowPos3dv");
    glWindowPos3f = wglGetProcAddress("glWindowPos3f");
    glWindowPos3fv = wglGetProcAddress("glWindowPos3fv");
    glWindowPos3i = wglGetProcAddress("glWindowPos3i");
    glWindowPos3iv = wglGetProcAddress("glWindowPos3iv");
    glWindowPos3s = wglGetProcAddress("glWindowPos3s");
    glWindowPos3sv = wglGetProcAddress("glWindowPos3sv");
    glGenQueries = wglGetProcAddress("glGenQueries");
    glDeleteQueries = wglGetProcAddress("glDeleteQueries");
    glIsQuery = wglGetProcAddress("glIsQuery");
    glBeginQuery = wglGetProcAddress("glBeginQuery");
    glEndQuery = wglGetProcAddress("glEndQuery");
    glGetQueryiv = wglGetProcAddress("glGetQueryiv");
    glGetQueryObjectiv = wglGetProcAddress("glGetQueryObjectiv");
    glGetQueryObjectuiv = wglGetProcAddress("glGetQueryObjectuiv");
    glBindBuffer = wglGetProcAddress("glBindBuffer");
    glDeleteBuffers = wglGetProcAddress("glDeleteBuffers");
    glGenBuffers = wglGetProcAddress("glGenBuffers");
    glIsBuffer = wglGetProcAddress("glIsBuffer");
    glBufferData = wglGetProcAddress("glBufferData");
    glBufferSubData = wglGetProcAddress("glBufferSubData");
    glGetBufferSubData = wglGetProcAddress("glGetBufferSubData");
    glMapBuffer = wglGetProcAddress("glMapBuffer");
    glUnmapBuffer = wglGetProcAddress("glUnmapBuffer");
    glGetBufferParameteriv = wglGetProcAddress("glGetBufferParameteriv");
    glGetBufferPointerv = wglGetProcAddress("glGetBufferPointerv");
    glBlendEquationSeparate = wglGetProcAddress("glBlendEquationSeparate");
    glDrawBuffers = wglGetProcAddress("glDrawBuffers");
    glStencilOpSeparate = wglGetProcAddress("glStencilOpSeparate");
    glStencilFuncSeparate = wglGetProcAddress("glStencilFuncSeparate");
    glStencilMaskSeparate = wglGetProcAddress("glStencilMaskSeparate");
    glAttachShader = wglGetProcAddress("glAttachShader");
    glBindAttribLocation = wglGetProcAddress("glBindAttribLocation");
    glCompileShader = wglGetProcAddress("glCompileShader");
    glCreateProgram = wglGetProcAddress("glCreateProgram");
    glCreateShader = wglGetProcAddress("glCreateShader");
    glDeleteProgram = wglGetProcAddress("glDeleteProgram");
    glDeleteShader = wglGetProcAddress("glDeleteShader");
    glDetachShader = wglGetProcAddress("glDetachShader");
    glDisableVertexAttribArray = wglGetProcAddress("glDisableVertexAttribArray");
    glEnableVertexAttribArray = wglGetProcAddress("glEnableVertexAttribArray");
    glGetActiveAttrib = wglGetProcAddress("glGetActiveAttrib");
    glGetActiveUniform = wglGetProcAddress("glGetActiveUniform");
    glGetAttachedShaders = wglGetProcAddress("glGetAttachedShaders");
    glGetAttribLocation = wglGetProcAddress("glGetAttribLocation");
    glGetProgramiv = wglGetProcAddress("glGetProgramiv");
    glGetProgramInfoLog = wglGetProcAddress("glGetProgramInfoLog");
    glGetShaderiv = wglGetProcAddress("glGetShaderiv");
    glGetShaderInfoLog = wglGetProcAddress("glGetShaderInfoLog");
    glGetShaderSource = wglGetProcAddress("glGetShaderSource");
    glGetUniformLocation = wglGetProcAddress("glGetUniformLocation");
    glGetUniformfv = wglGetProcAddress("glGetUniformfv");
    glGetUniformiv = wglGetProcAddress("glGetUniformiv");
    glGetVertexAttribdv = wglGetProcAddress("glGetVertexAttribdv");
    glGetVertexAttribfv = wglGetProcAddress("glGetVertexAttribfv");
    glGetVertexAttribiv = wglGetProcAddress("glGetVertexAttribiv");
    glGetVertexAttribPointerv = wglGetProcAddress("glGetVertexAttribPointerv");
    glIsProgram = wglGetProcAddress("glIsProgram");
    glIsShader = wglGetProcAddress("glIsShader");
    glLinkProgram = wglGetProcAddress("glLinkProgram");
    glShaderSource = wglGetProcAddress("glShaderSource");
    glUseProgram = wglGetProcAddress("glUseProgram");
    glUniform1f = wglGetProcAddress("glUniform1f");
    glUniform2f = wglGetProcAddress("glUniform2f");
    glUniform3f = wglGetProcAddress("glUniform3f");
    glUniform4f = wglGetProcAddress("glUniform4f");
    glUniform1i = wglGetProcAddress("glUniform1i");
    glUniform2i = wglGetProcAddress("glUniform2i");
    glUniform3i = wglGetProcAddress("glUniform3i");
    glUniform4i = wglGetProcAddress("glUniform4i");
    glUniform1fv = wglGetProcAddress("glUniform1fv");
    glUniform2fv = wglGetProcAddress("glUniform2fv");
    glUniform3fv = wglGetProcAddress("glUniform3fv");
    glUniform4fv = wglGetProcAddress("glUniform4fv");
    glUniform1iv = wglGetProcAddress("glUniform1iv");
    glUniform2iv = wglGetProcAddress("glUniform2iv");
    glUniform3iv = wglGetProcAddress("glUniform3iv");
    glUniform4iv = wglGetProcAddress("glUniform4iv");
    glUniformMatrix2fv = wglGetProcAddress("glUniformMatrix2fv");
    glUniformMatrix3fv = wglGetProcAddress("glUniformMatrix3fv");
    glUniformMatrix4fv = wglGetProcAddress("glUniformMatrix4fv");
    glValidateProgram = wglGetProcAddress("glValidateProgram");
    glVertexAttrib1d = wglGetProcAddress("glVertexAttrib1d");
    glVertexAttrib1dv = wglGetProcAddress("glVertexAttrib1dv");
    glVertexAttrib1f = wglGetProcAddress("glVertexAttrib1f");
    glVertexAttrib1fv = wglGetProcAddress("glVertexAttrib1fv");
    glVertexAttrib1s = wglGetProcAddress("glVertexAttrib1s");
    glVertexAttrib1sv = wglGetProcAddress("glVertexAttrib1sv");
    glVertexAttrib2d = wglGetProcAddress("glVertexAttrib2d");
    glVertexAttrib2dv = wglGetProcAddress("glVertexAttrib2dv");
    glVertexAttrib2f = wglGetProcAddress("glVertexAttrib2f");
    glVertexAttrib2fv = wglGetProcAddress("glVertexAttrib2fv");
    glVertexAttrib2s = wglGetProcAddress("glVertexAttrib2s");
    glVertexAttrib2sv = wglGetProcAddress("glVertexAttrib2sv");
    glVertexAttrib3d = wglGetProcAddress("glVertexAttrib3d");
    glVertexAttrib3dv = wglGetProcAddress("glVertexAttrib3dv");
    glVertexAttrib3f = wglGetProcAddress("glVertexAttrib3f");
    glVertexAttrib3fv = wglGetProcAddress("glVertexAttrib3fv");
    glVertexAttrib3s = wglGetProcAddress("glVertexAttrib3s");
    glVertexAttrib3sv = wglGetProcAddress("glVertexAttrib3sv");
    glVertexAttrib4Nbv = wglGetProcAddress("glVertexAttrib4Nbv");
    glVertexAttrib4Niv = wglGetProcAddress("glVertexAttrib4Niv");
    glVertexAttrib4Nsv = wglGetProcAddress("glVertexAttrib4Nsv");
    glVertexAttrib4Nub = wglGetProcAddress("glVertexAttrib4Nub");
    glVertexAttrib4Nubv = wglGetProcAddress("glVertexAttrib4Nubv");
    glVertexAttrib4Nuiv = wglGetProcAddress("glVertexAttrib4Nuiv");
    glVertexAttrib4Nusv = wglGetProcAddress("glVertexAttrib4Nusv");
    glVertexAttrib4bv = wglGetProcAddress("glVertexAttrib4bv");
    glVertexAttrib4d = wglGetProcAddress("glVertexAttrib4d");
    glVertexAttrib4dv = wglGetProcAddress("glVertexAttrib4dv");
    glVertexAttrib4f = wglGetProcAddress("glVertexAttrib4f");
    glVertexAttrib4fv = wglGetProcAddress("glVertexAttrib4fv");
    glVertexAttrib4iv = wglGetProcAddress("glVertexAttrib4iv");
    glVertexAttrib4s = wglGetProcAddress("glVertexAttrib4s");
    glVertexAttrib4sv = wglGetProcAddress("glVertexAttrib4sv");
    glVertexAttrib4ubv = wglGetProcAddress("glVertexAttrib4ubv");
    glVertexAttrib4uiv = wglGetProcAddress("glVertexAttrib4uiv");
    glVertexAttrib4usv = wglGetProcAddress("glVertexAttrib4usv");
    glVertexAttribPointer = wglGetProcAddress("glVertexAttribPointer");
    glUniformMatrix2x3fv = wglGetProcAddress("glUniformMatrix2x3fv");
    glUniformMatrix3x2fv = wglGetProcAddress("glUniformMatrix3x2fv");
    glUniformMatrix2x4fv = wglGetProcAddress("glUniformMatrix2x4fv");
    glUniformMatrix4x2fv = wglGetProcAddress("glUniformMatrix4x2fv");
    glUniformMatrix3x4fv = wglGetProcAddress("glUniformMatrix3x4fv");
    glUniformMatrix4x3fv = wglGetProcAddress("glUniformMatrix4x3fv");
    glColorMaski = wglGetProcAddress("glColorMaski");
    glGetBooleani_v = wglGetProcAddress("glGetBooleani_v");
    glGetIntegeri_v = wglGetProcAddress("glGetIntegeri_v");
    glEnablei = wglGetProcAddress("glEnablei");
    glDisablei = wglGetProcAddress("glDisablei");
    glIsEnabledi = wglGetProcAddress("glIsEnabledi");
    glBeginTransformFeedback = wglGetProcAddress("glBeginTransformFeedback");
    glEndTransformFeedback = wglGetProcAddress("glEndTransformFeedback");
    glBindBufferRange = wglGetProcAddress("glBindBufferRange");
    glBindBufferBase = wglGetProcAddress("glBindBufferBase");
    glTransformFeedbackVaryings = wglGetProcAddress("glTransformFeedbackVaryings");
    glGetTransformFeedbackVarying = wglGetProcAddress("glGetTransformFeedbackVarying");
    glClampColor = wglGetProcAddress("glClampColor");
    glBeginConditionalRender = wglGetProcAddress("glBeginConditionalRender");
    glEndConditionalRender = wglGetProcAddress("glEndConditionalRender");
    glVertexAttribI1i = wglGetProcAddress("glVertexAttribI1i");
    glVertexAttribI2i = wglGetProcAddress("glVertexAttribI2i");
    glVertexAttribI3i = wglGetProcAddress("glVertexAttribI3i");
    glVertexAttribI4i = wglGetProcAddress("glVertexAttribI4i");
    glVertexAttribI1ui = wglGetProcAddress("glVertexAttribI1ui");
    glVertexAttribI2ui = wglGetProcAddress("glVertexAttribI2ui");
    glVertexAttribI3ui = wglGetProcAddress("glVertexAttribI3ui");
    glVertexAttribI4ui = wglGetProcAddress("glVertexAttribI4ui");
    glVertexAttribI1iv = wglGetProcAddress("glVertexAttribI1iv");
    glVertexAttribI2iv = wglGetProcAddress("glVertexAttribI2iv");
    glVertexAttribI3iv = wglGetProcAddress("glVertexAttribI3iv");
    glVertexAttribI4iv = wglGetProcAddress("glVertexAttribI4iv");
    glVertexAttribI1uiv = wglGetProcAddress("glVertexAttribI1uiv");
    glVertexAttribI2uiv = wglGetProcAddress("glVertexAttribI2uiv");
    glVertexAttribI3uiv = wglGetProcAddress("glVertexAttribI3uiv");
    glVertexAttribI4uiv = wglGetProcAddress("glVertexAttribI4uiv");
    glVertexAttribI4bv = wglGetProcAddress("glVertexAttribI4bv");
    glVertexAttribI4sv = wglGetProcAddress("glVertexAttribI4sv");
    glVertexAttribI4ubv = wglGetProcAddress("glVertexAttribI4ubv");
    glVertexAttribI4usv = wglGetProcAddress("glVertexAttribI4usv");
    glVertexAttribIPointer = wglGetProcAddress("glVertexAttribIPointer");
    glGetVertexAttribIiv = wglGetProcAddress("glGetVertexAttribIiv");
    glGetVertexAttribIuiv = wglGetProcAddress("glGetVertexAttribIuiv");
    glGetUniformuiv = wglGetProcAddress("glGetUniformuiv");
    glBindFragDataLocation = wglGetProcAddress("glBindFragDataLocation");
    glGetFragDataLocation = wglGetProcAddress("glGetFragDataLocation");
    glUniform1ui = wglGetProcAddress("glUniform1ui");
    glUniform2ui = wglGetProcAddress("glUniform2ui");
    glUniform3ui = wglGetProcAddress("glUniform3ui");
    glUniform4ui = wglGetProcAddress("glUniform4ui");
    glUniform1uiv = wglGetProcAddress("glUniform1uiv");
    glUniform2uiv = wglGetProcAddress("glUniform2uiv");
    glUniform3uiv = wglGetProcAddress("glUniform3uiv");
    glUniform4uiv = wglGetProcAddress("glUniform4uiv");
    glTexParameterIiv = wglGetProcAddress("glTexParameterIiv");
    glTexParameterIuiv = wglGetProcAddress("glTexParameterIuiv");
    glGetTexParameterIiv = wglGetProcAddress("glGetTexParameterIiv");
    glGetTexParameterIuiv = wglGetProcAddress("glGetTexParameterIuiv");
    glClearBufferiv = wglGetProcAddress("glClearBufferiv");
    glClearBufferuiv = wglGetProcAddress("glClearBufferuiv");
    glClearBufferfv = wglGetProcAddress("glClearBufferfv");
    glClearBufferfi = wglGetProcAddress("glClearBufferfi");
    glIsRenderbuffer = wglGetProcAddress("glIsRenderbuffer");
    glBindRenderbuffer = wglGetProcAddress("glBindRenderbuffer");
    glDeleteRenderbuffers = wglGetProcAddress("glDeleteRenderbuffers");
    glGenRenderbuffers = wglGetProcAddress("glGenRenderbuffers");
    glRenderbufferStorage = wglGetProcAddress("glRenderbufferStorage");
    glGetRenderbufferParameteriv = wglGetProcAddress("glGetRenderbufferParameteriv");
    glIsFramebuffer = wglGetProcAddress("glIsFramebuffer");
    glBindFramebuffer = wglGetProcAddress("glBindFramebuffer");
    glDeleteFramebuffers = wglGetProcAddress("glDeleteFramebuffers");
    glGenFramebuffers = wglGetProcAddress("glGenFramebuffers");
    glCheckFramebufferStatus = wglGetProcAddress("glCheckFramebufferStatus");
    glFramebufferTexture1D = wglGetProcAddress("glFramebufferTexture1D");
    glFramebufferTexture2D = wglGetProcAddress("glFramebufferTexture2D");
    glFramebufferTexture3D = wglGetProcAddress("glFramebufferTexture3D");
    glFramebufferRenderbuffer = wglGetProcAddress("glFramebufferRenderbuffer");
    glGetFramebufferAttachmentParameteriv = wglGetProcAddress("glGetFramebufferAttachmentParameteriv");
    glGenerateMipmap = wglGetProcAddress("glGenerateMipmap");
    glBlitFramebuffer = wglGetProcAddress("glBlitFramebuffer");
    glRenderbufferStorageMultisample = wglGetProcAddress("glRenderbufferStorageMultisample");
    glFramebufferTextureLayer = wglGetProcAddress("glFramebufferTextureLayer");
    glFlushMappedBufferRange = wglGetProcAddress("glFlushMappedBufferRange");
    glBindVertexArray = wglGetProcAddress("glBindVertexArray");
    glDeleteVertexArrays = wglGetProcAddress("glDeleteVertexArrays");
    glGenVertexArrays = wglGetProcAddress("glGenVertexArrays");
    glIsVertexArray = wglGetProcAddress("glIsVertexArray");
    glDrawArraysInstanced = wglGetProcAddress("glDrawArraysInstanced");
    glDrawElementsInstanced = wglGetProcAddress("glDrawElementsInstanced");
    glPrimitiveRestartIndex = wglGetProcAddress("glPrimitiveRestartIndex");
    glTexBuffer = wglGetProcAddress("glTexBuffer");
    glCopyBufferSubData = wglGetProcAddress("glCopyBufferSubData");
    glGetActiveUniformBlockName = wglGetProcAddress("glGetActiveUniformBlockName");
    glGetActiveUniformBlockiv = wglGetProcAddress("glGetActiveUniformBlockiv");
    glGetActiveUniformName = wglGetProcAddress("glGetActiveUniformName");
    glGetActiveUniformsiv = wglGetProcAddress("glGetActiveUniformsiv");
    glGetUniformBlockIndex = wglGetProcAddress("glGetUniformBlockIndex");
    glGetUniformIndices = wglGetProcAddress("glGetUniformIndices");
    glUniformBlockBinding = wglGetProcAddress("glUniformBlockBinding");
    glFramebufferTexture = wglGetProcAddress("glFramebufferTexture");
    glFramebufferTextureFace = wglGetProcAddress("glFramebufferTextureFace");
    glGetBufferParameteri64v = wglGetProcAddress("glGetBufferParameteri64v");
    glGetInteger64i_v = wglGetProcAddress("glGetInteger64i_v");
    glProgramParameteri = wglGetProcAddress("glProgramParameteri");
    glDrawElementsBaseVertex = wglGetProcAddress("glDrawElementsBaseVertex");
    glDrawElementsInstancedBaseVertex = wglGetProcAddress("glDrawElementsInstancedBaseVertex");
    glDrawRangeElementsBaseVertex = wglGetProcAddress("glDrawRangeElementsBaseVertex");
    glMultiDrawElementsBaseVertex = wglGetProcAddress("glMultiDrawElementsBaseVertex");
    glProvokingVertex = wglGetProcAddress("glProvokingVertex");
    glClientWaitSync = wglGetProcAddress("glClientWaitSync");
    glDeleteSync = wglGetProcAddress("glDeleteSync");
    glFenceSync = wglGetProcAddress("glFenceSync");
    glGetInteger64v = wglGetProcAddress("glGetInteger64v");
    glGetSynciv = wglGetProcAddress("glGetSynciv");
    glIsSync = wglGetProcAddress("glIsSync");
    glWaitSync = wglGetProcAddress("glWaitSync");
    glGetMultisamplefv = wglGetProcAddress("glGetMultisamplefv");
    glTexImage2DMultisample = wglGetProcAddress("glTexImage2DMultisample");
    glTexImage3DMultisample = wglGetProcAddress("glTexImage3DMultisample");
    glSampleMaski = wglGetProcAddress("glSampleMaski");
}